### ISSUE TITLE
how to use?

### ISSUE THREAD

**Issue by Jasperty** [polLiosis/Sentence_Selection_for_QA#1]

**Comment by polLiosis** [comment]
First of all, you should download and create the train/test datasets from the BioASQ json files. In order to do that, you have to run the **main.py** and **improve_train_set.py** / **improve_test_set.py** scripts in Extract_BioASQ_data folder.
After the extraction of the snippets with the above method, you transfer the new text files in the dataset folder of the respective DL model.
